services:
  backend_test:
    container_name: inf_mgr_backend_test
    build:
      context: .
      dockerfile: ./tests/Dockerfile
    env_file:
      - .env.test
    ports:
      - "8001:8001"
    networks:
      - my_networks
    depends_on:
      - postgres_test
    volumes:
      - .:/app
      - cargo_cache:/usr/local/cargo/registry
      - rust_target_cache:/app/target
    command: sh -c "cd /app/tests && ln -sf ../apps/server/config config && ln -sf ../apps/server/tools tools && tail -f /dev/null"

  postgres_test:
    container_name: inf_mgr_postgres_test
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    extends:
      file: docker-compose.base.yml
      service: postgres_base
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    env_file:
      - .env.test
    networks:
      - my_networks

networks:
  my_networks:
    driver: bridge

volumes:
  postgres_data_test:
  server_target:
  cargo_cache:
  rust_target_cache:
