services:
  server_test:
    container_name: inf_mgr_server_test
    extends:
      file: docker-compose.base.yml
      service: server_base
    build:
      target: test
    env_file:
      - .env.test
    depends_on:
      - postgres_test

  postgres_test:
    container_name: inf_mgr_postgres_test
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    extends:
      file: docker-compose.base.yml
      service: postgres_base
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    env_file:
      - .env.test
    networks:
      - my_networks

networks:
  my_networks:
    driver: bridge

volumes:
  postgres_data_test:
  server_target:
  cargo_cache:
