[application]
port = 8000
host = "0.0.0.0"
body_limit = "5MB"
request_timeout_seconds = 15
graceful_shutdown = false

client_app_url = "${PUBLIC_URL:http://localhost:3000}"
documents_dir = "${DOCUMENTS_DIR:./documents}"

[event-queue]
buffer_size = 100
num_of_event_retry = 2
delay_between_event_retry_ms = 2000

[postgres-db]
url = "${POSTGRES_DATABASE_URL:postgres://localhost:5432/inf_mgr}"
migration_path = "config/migrations"
min_connections = 1
max_connections = 10
acquire_timeout_ms = 5000

[redis]
url = "${REDIS_DATABASE_URL}"

[auth]
access_jwt_secret = "${ACCESS_JWT_SECRET}"
refresh_jwt_secret = "${REFRESH_JWT_SECRET}"

access_exp_ms = 120000    # 2 minutes (for testing)
refresh_exp_ms = 600000   # 10 minutes (for testing)
session_ttl_seconds = 600 # 10 minutes (for testing)

# access_exp_ms = 900000       # 15 minutes
# refresh_exp_ms = 604800000   # 7 days
# session_ttl_seconds = 604800 # 7 days

google_client_id = "${GOOGLE_CLIENT_ID}"
google_client_secret = "${GOOGLE_CLIENT_SECRET}"
google_redirect_url = "${GOOGLE_REDIRECT_URL}"

[google-calendar]
calendar_id = "${GOOGLE_CALENDAR_ID}"
service_account_path = "${GOOGLE_SERVICE_ACCOUNT_PATH}"

[cors]
allow_credentials = false
allow_methods = ["GET", "POST", "PUT", "PATCH", "DELETE"]
allow_headers = ["Content-Type", "Authorization"]

[services-config]

[services-config.mailer]
smtp_host = "${SMTP_HOST:localhost}"
smtp_port = "${SMTP_PORT}"
smtp_username = "${SMTP_USERNAME}"
smtp_password = "${SMTP_PASSWORD}"

[services-config.templates]
public_url = "${PUBLIC_URL:http://localhost:8000}"
career_name = "${CAREER_NAME:Ingeniería en Informática}"
career_manager = "${CAREER_MANAGER:Director de Carrera}"
secretary_email = "${SECRETARY_EMAIL}"

[services-config.printer]
documents_dir = "${DOCUMENTS_DIR:./documents}"

[services-config.zipper]
extract_base_dir = "${DOCUMENTS_DIR:./documents}"
