[application]
port = 8000
host = "0.0.0.0"

[postgres-db]
url = "${POSTGRES_DATABASE_URL:postgres://localhost:5432/inf_mgr}"
migration_path = "config/migrations"
min_connections = 1
max_connections = 10
acquire_timeout_ms = 5000

[auth]
session_jwt_secret = "${SESSION_JWT_SECRET}"
session_jwt_exp_ms = 900000                  # 15 minutes

refresh_jwt_secret = "${REFRESH_JWT_SECRET}"
refresh_jwt_exp_ms = 604800000               # 7 days

[cors]
allow_credentials = false
allowed_http_methods = ["GET", "POST", "PUT", "PATCH", "DELETE"]
allowed_http_headers = ["Content-Type", "Authorization"]
