[package]
name = "server"
version = "0.1.0"
edition = "2024"

[features]
default = []
seeder = ["dep:fake", "dep:rand"]

[[bin]]
name = "seeder"
path = "tools/seeder/main.rs"
required-features = ["seeder"]

[dependencies]
tokio = { version = "1.46.1", features = ["full"] }

oauth2 = "5.0.0"
reqwest = { version = "0.12", features = ["json"] }
sword = { git = "https://github.com/MrRevillod/sword.git", branch = "main", features = [
    "multipart",
    "cookies",
    "helmet",
    "validator",
] }

services = { path = "../../packages/services" }
tex_parser = { path = "../../packages/tex_parser" }

filterstruct = "0.1.0"
chrono = { version = "0.4.41", features = ["serde"] }

uuid = { version = "1.17.0", features = ["serde", "v4"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

redis = { version = "0.32.5", features = ["tokio-comp"] }
sqlx = { version = "0.8.6", default-features = false, features = [
    "runtime-tokio",
    "postgres",
    "chrono",
    "uuid",
    "derive",
    "migrate",
    "macros",
] }

tower-http = { version = "0.6.6", features = ["trace"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

validator = { version = "0.20.0", features = ["derive"] }
regex = "1.11.1"

fake = { version = "4.3.0", optional = true }
rand = { version = "0.9.1", optional = true }

thiserror = "2.0.14"

jsonwebtoken = "9.3.1"
time = "0.3.43"
futures = "0.3.31"
bytes = "1.10.1"
infer = "0.19.0"
