use crate::types::*;

pub static PRINTER_TEMPLATES: LazyLock<Templates> = LazyLock::new(|| {
    vec![(
        "document:practice:authorization",
        include_str!("../printer/templates/authorization.typ"),
    )]
});

pub static MAILER_TEMPLATES: LazyLock<Templates> = LazyLock::new(|| {
    vec![
        ("base.html", include_str!("../mailer/templates/base.html")),
        (
            "system:welcome.html",
            include_str!("../mailer/templates/system/welcome.html"),
        ),
        (
            "practice:creation:supervisor.html",
            include_str!("../mailer/templates/practice/creation/supervisor.html"),
        ),
        (
            "practice:creation:student.html",
            include_str!("../mailer/templates/practice/creation/student.html"),
        ),
        (
            "practice:creation:secretary.html",
            include_str!("../mailer/templates/practice/creation/secretary.html"),
        ),
        (
            "practice:approval:supervisor.html",
            include_str!("../mailer/templates/practice/approval/supervisor.html"),
        ),
        (
            "practice:approval:teacher.html",
            include_str!("../mailer/templates/practice/approval/teacher.html"),
        ),
        (
            "practice:approval:student.html",
            include_str!("../mailer/templates/practice/approval/student.html"),
        ),
        (
            "practice:decline:supervisor.html",
            include_str!("../mailer/templates/practice/decline/supervisor.html"),
        ),
        (
            "practice:approval:secretary.html",
            include_str!("../mailer/templates/practice/approval/secretary.html"),
        ),
        (
            "practice:decline:student.html",
            include_str!("../mailer/templates/practice/decline/student.html"),
        ),
        (
            "practice:decline:secretary.html",
            include_str!("../mailer/templates/practice/decline/secretary.html"),
        ),
        (
            "practice:decline:teacher.html",
            include_str!("../mailer/templates/practice/decline/teacher.html"),
        ),
        (
            "practice:evaluation:supervisor.html",
            include_str!("../mailer/templates/practice/evaluation/supervisor.html"),
        ),
        (
            "practice:evaluation:teacher.html",
            include_str!("../mailer/templates/practice/evaluation/teacher.html"),
        ),
        (
            "course:creation:teacher.html",
            include_str!("../mailer/templates/course/creation/teacher.html"),
        ),
        (
            "report-upload:teacher.html",
            include_str!("../mailer/templates/report-upload/teacher.html"),
        ),
        (
            "report-upload:student.html",
            include_str!("../mailer/templates/report-upload/student.html"),
        ),
        (
            "authorization:secretary.html",
            include_str!("../mailer/templates/authorization/secretary.html"),
        ),
        (
            "authorization:teacher.html",
            include_str!("../mailer/templates/authorization/teacher.html"),
        ),
        (
            "meeting-req:creation:teacher.html",
            include_str!("../mailer/templates/meeting-req/creation/teacher.html"),
        ),
    ]
});
