port 6379
bind 0.0.0.0

# Save snapshots every 60 seconds if at least 1 key changed (for development)
save 60 1
appendonly yes

maxmemory 256mb
maxmemory-policy allkeys-lru 

loglevel warning
syslog-enabled no
